admin-api-key = ''
album-path-joiner = ' / '
album-picasa = false
api-key = ''
api-trace = false
ban-file = "'@eaDir/', '@__thumb/', 'SYNOFILE_THUMB_*.*', 'Lightroom Catalog/', 'thumbnails/', '.DS_Store/', '/._*', '.photostructure/'"
client-timeout = '20m0s'
concurrent-uploads = 12
date-from-name = true
date-range = 'unset'
device-uuid = 'gl65'
dry-run = false
exclude-extensions = ''
folder-as-album = 'NONE'
folder-as-tags = false
from-album-name = ''
from-api-key = ''
from-api-trace = false
from-archived = false
from-client-timeout = '20m0s'
from-date-range = 'unset'
from-favorite = false
from-minimal-rating = 0
from-server = ''
from-skip-verify-ssl = false
from-trash = false
ignore-sidecar-files = false
include-archived = true
include-extensions = ''
include-partner = true
include-trashed = false
include-type = ''
include-unmatched = false
include-untitled-albums = false
into-album = ''
manage-burst = 'NoStack'
manage-epson-fastfoto = false
manage-heic-jpeg = 'NoStack'
manage-raw-jpeg = 'NoStack'
memories = false
no-ui = false
on-server-errors = 'stop'
overwrite = false
partner-shared-album = ''
pause-immich-jobs = true
people-tag = true
recursive = true
server = ''
session-tag = false
skip-verify-ssl = false
sync-albums = true
tag = []
takeout-tag = true
time-zone = ''
